cas: Enable OF_USE_DMCTL - https://gitlab.com/OrangeFox/vendor/recovery/-/blob/fox_12.1/orangefox_build_vars.txt?ref_type=heads#L893  - set this to 1 if you want to use 'dmctl' (as an alternative to 'dmsetup') to try and work around problems with formatting the /data partition    - if this is enabled, the dmsetup binary will be built into the recovery, and will be called just before formatting /data    - this is only useful for devices/ROMs that have dynamic partitions
- This fixes the error we get during format data like below:

I:mkfs_f2fs command: /system/bin/make_f2fs -g android -O project_quota,extra_attr -O casefold -C utf8 /dev/block/sda34 59291639 && sload_f2fs -t /data /dev/block/sda34

	F2FS-tools: mkfs.f2fs Ver: 1.14.0 (2020-08-24)

Info: Disable heap-based policy
Info: Debug level = 1
Info: Trim is enabled
Info: Set conf for android
Info: Enable utf8 with casefolding
Info: Enable Project quota
	Error: In use by the system!
/system/bin/make_f2fs -g android -O project_quota,extra_attr -O casefold -C utf8 /dev/block/sda34 59291639 && sload_f2fs -t /data /dev/block/sda34 process ended with ERROR: 255
Unable to wipe Data.
Unable to format to remove encryption.
I:Can't probe device /dev/block/sda34
I:Unable to mount '/data'

- With flag enabled we see successful data format:

I:mkfs_f2fs command: /system/bin/make_f2fs -g android -O project_quota,extra_attr -O casefold -C utf8 /dev/block/sda34 59291639 && sload_f2fs -t /data /dev/block/sda34
I:OrangeFox: running dmctl before formatting...

	F2FS-tools: mkfs.f2fs Ver: 1.14.0 (2020-08-24)

Info: Disable heap-based policy
Info: Debug level = 1
Info: Trim is enabled
Info: Set conf for android
Info: Enable utf8 with casefolding
Info: Enable Project quota
	Info: No support kernel version!
Info: wanted sectors = 59291639 (in 4096 bytes)
Info: total device sectors = 59291643 (in 4096 bytes)
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 4096
Info: total sectors = 59291639 (231607 MB)
Info: zone aligned segment0 blkaddr: 512
Info: add quota type = 0 => 4
Info: add quota type = 1 => 5
Info: add quota type = 2 => 6
Info: [/dev/block/sda34] Discarding device
Info: This device doesn't support BLKSECDISCARD
Info: Discarded 231607 MB
[f2fs_init_sit_area: 619] 	Filling sit area at offset 0x00600000
[f2fs_init_nat_area: 653] 	Filling nat area at offset 0x01a00000
[f2fs_write_root_inode:1266] 	Writing root inode (hot node), 2ba00 0 200 at offset 0x00178688
[f2fs_write_default_quota:1342] 	Writing quota data, at offset 0002c001, 0002c002
[f2fs_write_qf_inode:1433] 	Writing quota inode (hot node), 2ba00 0 200 at offset 0x00178689
[f2fs_write_default_quota:1342] 	Writing quota data, at offset 0002c003, 0002c004
[f2fs_write_qf_inode:1433] 	Writing quota inode (hot node), 2ba00 0 200 at offset 0x00178690
[f2fs_write_default_quota:1342] 	Writing quota data, at offset 0002c005, 0002c006
[f2fs_write_qf_inode:1433] 	Writing quota inode (hot node), 2ba00 0 200 at offset 0x00178691
[f2fs_update_nat_root:1487] 	Writing nat root, at offset 0x00001a00
[f2fs_add_default_dentry_root:1684] 	Writing default dentry root, at offset 0x0002c000
Info: Overprovision ratio = 0.420%
Info: Overprovision segments = 966 (GC reserved = 484)
[f2fs_write_check_point_pack: 812] 	Writing main segments, cp at offset 0x00000200
[f2fs_write_check_point_pack: 967] 	Writing Segment summary for HOT/WARM/COLD_DATA, at offset 0x00000201
[f2fs_write_check_point_pack: 994] 	Writing Segment summary for HOT_NODE, at offset 0x00000202
[f2fs_write_check_point_pack:1006] 	Writing Segment summary for WARM_NODE, at offset 0x00000203
[f2fs_write_check_point_pack:1017] 	Writing Segment summary for COLD_NODE, at offset 0x00000204
[f2fs_write_check_point_pack:1025] 	Writing cp page2, at offset 0x00000205
[f2fs_write_check_point_pack:1045] 	Writing NAT bits pages, at offset 0x000003fe
[f2fs_write_check_point_pack:1066] 	Writing cp page 1 of checkpoint pack 2, at offset 0x00000400
[f2fs_write_check_point_pack:1085] 	Writing cp page 2 of checkpoint pack 2, at offset 0x00000405
[f2fs_write_super_block:1118] 	Writing super block, at offset 0x00000000
Info: format successful
	Info: No support kernel version!
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 4096
Info: total sectors = 59291643 (231607 MB)
Info: MKFS version
  "4.19.325-perf+"
Info: FSCK version
  from "4.19.325-perf+"
    to "4.19.325-perf+"
Info: version timestamp cur: 1768029287, prev: 0
[update_superblock: 706] Info: Done to update superblock
Info: superblock features = 1499 :  encrypt verity extra_attr project_quota quota_ino casefold
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 59291639 (231607 MB)
Info: CKPT version = 71e4905d
Info: No source directory, but it's okay.
Info: MKFS version
  "4.19.325-perf+"
Info: FSCK version
  from "4.19.325-perf+"
    to "4.19.325-perf+"
Info: version timestamp cur: 1768029288, prev: 1768029287
Info: superblock features = 1499 :  encrypt verity extra_attr project_quota quota_ino casefold
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 59291639 (231607 MB)
Info: CKPT version = 71e4905d
Info: Corrupted valid nat_bits in checkpoint
Info: Write valid nat_bits in checkpoint
Info: checkpoint state = 185 :  trimmed nat_bits compacted_summary unmount

[FSCK] Max image size: 704 MB, Free space: 228975 MB
[FSCK] Unreachable nat entries                        [Ok..] [0x0]
[FSCK] SIT valid block bitmap checking                [Ok..]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Ok..] [0xb]
[FSCK] valid_node_count matching with CP (de lookup)  [Ok..] [0x4]
[FSCK] valid_node_count matching with CP (nat lookup) [Ok..] [0x4]
[FSCK] valid_inode_count matched with CP              [Ok..] [0x4]
[FSCK] free segment_count matched with CP             [Ok..] [0x1c2f8]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Ok..]
Info: Duplicate valid checkpoint to mirror position 512 -> 1024
Info: Write valid nat_bits in checkpoint
Info: Write valid nat_bits in checkpoint

Done: 0.759278 secs
I:Process ended with no errors.
Done
You may need to reboot recovery to be able to use /data again.
OrangeFox will not recreate /data/media on an FBE device. Please reboot into your rom to create /data/media
Formatting Metadata using mke2fs...
I:mke2fs command: mke2fs -t ext4 -b 4096 -I 512 /dev/block/sda18 4096
mke2fs 1.45.4 (23-Sep-2019)
Discarding device blocks:          done
Creating filesystem with 4096 4k blocks and 4096 inodes

Allocating group tables: 0/1   done
Writing inode tables: 0/1   done
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: 0/1   done

I:Process ended with no errors.
I:e2fsdroid command: e2fsdroid -e -S /file_contexts -a /metadata /dev/block/sda18
SELinux: Loaded file_contexts
Created filesystem with 11/4096 inodes and 1547/4096 blocks
I:Process ended with no errors.
Done
Updating partition details...
I:Data backup size is 0MB, free: 228975MB.
...done
I:Set page: 'wipe_action_complete'
I:operation_end - status=0
I:TWFunc::Set_Brightness: Setting brightness control to 5
I:TWFunc::Set_Brightness: Setting brightness control to 0